Adapt to updated monasca-grafana-plugin
monasca/grafana pull request #1
Opened 2018-01-16 12:47 UTC by jgrassler

This commit adds (backwards compatible) support for the new
auth mechanism selection mechanism introduced in
monasca-grafana-datasource by

  https://github.com/openstack/monasca-grafana-datasource/commit/bb5178406c03d37a957b64ef59c61ecdec504fc3

Note: the `monasca-grafana-datasource` commit in question has recently been [reverted](https://review.openstack.org/#/c/529620/) because it breaks without the code from this pull
request in Grafana. I tested this pull request with both the reverted and the unreverted state and it works.

2018-01-17 12:11 UTC, matrixik requested changes
Code is not formated with `gofmt -s`. You could check what's the difference with `gofmt -s -d dataproxy.go`.

Other than that looks good. Not sure if I will be able to test it today but definitely I will test it tomorrow.

2018-01-17 13:11 UTC, jgrassler commented
Sorry, forgot about that one. Formatting is fixed now.

2018-01-17 16:04 UTC, witekest commented
Backwards compatibility works. Freshly stacked with:

```
GRAFANA_REPO=https://github.com/jgrassler/grafana.git
GRAFANA_BRANCH=grafana4-datasource-with-horizon-patch
```

and old (reverted) datasource works as expected.

2018-01-17 17:28 UTC, witekest commented
Tested as well with:

```
GRAFANA_REPO=https://github.com/jgrassler/grafana.git
GRAFANA_BRANCH=grafana4-datasource-with-horizon-patch
MONASCA_GRAFANA_DATASOURCE_BRANCH=refs/changes/89/534289/1
```

2018-01-18 05:22 UTC, matrixik approved these changes

2018-01-18 05:24 UTC, merged

2018-01-18 05:24 UTC, matrixik commented
Merging based om @witekest tests.
Thank you for fixing this.